### PR TITLE
Created dummy visits route

### PR DESCRIPTION
**Pull request by Het7**
## Notion ticket link

[Add dummy create /visits route](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=67b4525e53e040f6904f9984b13032cd)

## Implementation description
* Created a new `app/rest/visit_routes.py` file in order to create the `visits` route

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by jennchenn — CHANGES_REQUESTED** [review]
great job on your first PR ⭐ a few nits
you'll also need to register the route in [this file ](https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/rest/__init__.py) to be able to query it (i.e. `curl -X POST http://localhost:5000/visits`) - just follow the other examples in the file

**Comment by Het7** [comment]
> great job on your first PR ⭐ a few nits you'll also need to register the route in [this file ](https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/rest/__init__.py) to be able to query it (i.e. `curl -X POST http://localhost:5000/visits`) - just follow the other examples in the file

**Comment by Het7** [comment]
> great job on your first PR ⭐ a few nits you'll also need to register the route in [this file ](https://github.com/uwblueprint/childrens-aid-society/blob/main/backend/python/app/rest/__init__.py) to be able to query it (i.e. `curl -X POST http://localhost:5000/visits`) - just follow the other examples in the file

Thanks for the quick review Jennifer. I've made the changes as requested, thanks!

**Review by jennchenn — CHANGES_REQUESTED** [review]
got an error when starting up my container, but i think if you change the method names to match, they should work! last thing then it's good to merge :)

**Review by jennchenn — APPROVED** [review]
LGTM!! nice work 🚢

**Pull request merged**
