### PR TITLE
Created footer

### PR DESCRIPTION
**Pull request by Het7**
## Notion ticket link
[Create intake form footer navigation component](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=3e8a3cb2f18742fa91e7f69326a78bdc&pm=s)

## Implementation description
* Created a new component
Screen Shot 2022-10-25 at 9 23 52 PM

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by jennchenn — CHANGES_REQUESTED** [review]
talked about it during the meeting but putting this here for transparency:
* please update from main
* the footer should be replacing the prev/next buttons at the bottom of the page
 
please request re-review when addressed!!

**Comment by Het7** [comment]
> 

Addressed!

**Review by jennchenn — CHANGES_REQUESTED** [review]
1. the footer doesn't seem to always stick to the bottom of the page (see screenshot)
image
2. the buttons don't seem to be aligned to the right when the page is resized (see screenshot) - take a look at [this](https://www.figma.com/file/1obAgfYZ639hpKXV1ZP7hJ/3.-FeatureSets-%3E-Case-intake?node-id=1801%3A208121) for reference
3. on the last page, the button text changes to 'Review case details' and the 'Clear page' button does not exist - can you look into adding support to enable this (i.e. allowing user to change the button text, optionally remove the tertiary button, pass in a different button function for the last page)?

**Review by bowenzhu1 — CHANGES_REQUESTED** [review]
should remove the package-lock.json and yarn lock from the commit - will review more in detail in a bit

also, can we look more into/discuss how to save the entered information when navigating between steps? With the current implementation, the info gets lost when going to the next step, which is because we're no longer actually using the page specific submit functions

**Comment by bowenzhu1** [comment]
closing in favor of #134

**Pull request closed without merging**
